# Data Processing Pipeline Workflow
# This workflow demonstrates a sequential data processing pipeline
# with dependencies between steps

name: data-pipeline
description: End-to-end data processing pipeline for analytics

triggers:
  patterns:
    - ".*process.*data.*pipeline.*"
    - ".*analyze.*dataset.*"
    - ".*ETL.*pipeline.*"
  keywords:
    - data
    - pipeline
    - analytics
  intents:
    - data_processing
    - analytics_pipeline

variables:
  batch_size: "1000"
  output_format: "parquet"
  quality_threshold: "0.95"

steps:
  - name: validate-source
    agent: validator-agent
    namespace: data-quality
    instruction: "Validate data source connectivity and schema with quality threshold {{.quality_threshold}}"
    required: true
    timeout: "30s"

  - name: extract-data
    agent: extractor-agent
    namespace: etl
    instruction: "Extract data from source in batches of {{.batch_size}} records"
    depends_on:
      - validate-source
    required: true
    timeout: "5m"

  - name: transform-data
    agent: transformer-agent
    namespace: etl
    instruction: "Apply business logic transformations and data cleansing"
    depends_on:
      - extract-data
    required: true
    timeout: "10m"
    variables:
      transformation_rules: "standard_business_rules_v2"

  - name: quality-check
    agent: quality-agent
    namespace: data-quality
    instruction: "Perform data quality checks and generate quality report"
    depends_on:
      - transform-data
    parallel: true
    required: false
    timeout: "2m"

  - name: load-data
    agent: loader-agent
    namespace: etl
    instruction: "Load transformed data to destination in {{.output_format}} format"
    depends_on:
      - transform-data
    required: true
    timeout: "5m"

  - name: generate-report
    agent: reporter-agent
    namespace: analytics
    instruction: "Generate pipeline execution report with metrics and statistics"
    depends_on:
      - quality-check
      - load-data
    required: false
    timeout: "1m"

on_error: "rollback_and_notify"