# Parallel Search Workflow
# Demonstrates parallel execution of multiple agents
# for comprehensive search across different sources

name: parallel-search
description: Search multiple data sources in parallel and aggregate results

triggers:
  patterns:
    - ".*search.*everywhere.*"
    - ".*find.*all.*sources.*"
    - ".*comprehensive.*search.*"
  keywords:
    - search
    - find
    - lookup
  intents:
    - comprehensive_search
    - multi_source_query

steps:
  - name: search-database
    agent: database-agent
    namespace: backend
    instruction: "Search database for: {{.search_query}}"
    parallel: true
    required: false
    timeout: "10s"

  - name: search-cache
    agent: cache-agent
    namespace: backend
    instruction: "Search Redis cache for: {{.search_query}}"
    parallel: true
    required: false
    timeout: "5s"

  - name: search-elasticsearch
    agent: elastic-agent
    namespace: search
    instruction: "Search Elasticsearch index for: {{.search_query}}"
    parallel: true
    required: false
    timeout: "8s"

  - name: search-files
    agent: filesystem-agent
    namespace: storage
    instruction: "Search filesystem for: {{.search_query}}"
    parallel: true
    required: false
    timeout: "15s"

  - name: search-api
    agent: api-agent
    namespace: external
    instruction: "Search external API for: {{.search_query}}"
    parallel: true
    required: false
    timeout: "20s"

  - name: aggregate-results
    agent: aggregator-agent
    namespace: processing
    instruction: "Aggregate and rank all search results by relevance"
    depends_on:
      - search-database
      - search-cache
      - search-elasticsearch
      - search-files
      - search-api
    required: true
    timeout: "5s"

  - name: format-output
    agent: formatter-agent
    namespace: frontend
    instruction: "Format aggregated results for presentation"
    depends_on:
      - aggregate-results
    required: true
    timeout: "2s"